#!/usr/bin/env bash
# Local build script — concatenates src/ files into driver.lua, then packages
# room_control_webhook.c4z using snap-one/drivers-driverpackager (dp3).
# Requires: Python 3, lxml (`pip3 install lxml`), luac, git
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

DP3="tools/driverpackager/dp3/driverpackager.py"

if [[ ! -f "$DP3" ]]; then
  echo "Cloning snap-one/drivers-driverpackager into tools/driverpackager..."
  mkdir -p tools
  git clone --depth=1 https://github.com/snap-one/drivers-driverpackager tools/driverpackager
fi

# ---------------------------------------------------------------------------
# Step 1: Concatenate source files into driver.lua
# ---------------------------------------------------------------------------

echo "Concatenating src/ -> driver.lua..."
{
  echo '-- Room Control Webhook Driver'
  echo '-- AUTO-GENERATED by build.sh — edit files in src/ instead.'
  echo '---@diagnostic disable: undefined-global'
  for f in src/*.lua; do
    echo
    cat "$f"
  done
} > driver.lua
echo "  OK  driver.lua ($(wc -l < driver.lua) lines)"
echo

# Validate Lua syntax before packaging.
echo "Validating Lua..."
luac -p driver.lua
echo "  OK  driver.lua"
echo

# ---------------------------------------------------------------------------
# Step 2: Stamp driver.xml with build date and version
# ---------------------------------------------------------------------------

echo "Stamping driver.xml..."
BUILD_DATE=$(date +"%m/%d/%Y %H:%M")
VERSION=$(git rev-list --count HEAD 2>/dev/null || echo "1")
sed -i '' "s|<modified>.*</modified>|<modified>${BUILD_DATE}</modified>|" driver.xml
sed -i '' "s|<version>[^<]*</version>|<version>${VERSION}</version>|" driver.xml
echo "  version=${VERSION}  modified=${BUILD_DATE}"
echo

# ---------------------------------------------------------------------------
# Step 3: Package with snap-one driverpackager (dp3)
# ---------------------------------------------------------------------------

echo "Running driverpackager..."
python3 "$DP3" -v . . room_control_webhook.c4zproj

C4Z="room_control_webhook.c4z"
echo
echo "Built: $C4Z ($(wc -c < "$C4Z" | tr -d ' ') bytes)"
