-- Button ID → command mappings for C4:SendToDevice().
-- Keys are Control4 IR/serial button IDs; values list which DriverWorks
-- command fires on DO_PUSH / DO_RELEASE / DO_CLICK.
local BUTTONS = {
	[303] = {DO_PUSH = 'NUMBER_0'},
	[304] = {DO_PUSH = 'NUMBER_1'},
	[305] = {DO_PUSH = 'NUMBER_2'},
	[306] = {DO_PUSH = 'NUMBER_3'},
	[307] = {DO_PUSH = 'NUMBER_4'},
	[308] = {DO_PUSH = 'NUMBER_5'},
	[309] = {DO_PUSH = 'NUMBER_6'},
	[310] = {DO_PUSH = 'NUMBER_7'},
	[311] = {DO_PUSH = 'NUMBER_8'},
	[312] = {DO_PUSH = 'NUMBER_9'},
	[326] = {DO_PUSH = 'START_SCAN_FWD', DO_RELEASE = 'STOP_SCAN_FWD', DO_CLICK = 'STOP_SCAN_FWD'},
	[334] = {DO_PUSH = 'MUTE_ON'},
	[333] = {DO_PUSH = 'MUTE_OFF'},
	[335] = {DO_PUSH = 'MUTE_TOGGLE'},
	[344] = {DO_PUSH = 'PAUSE'},
	[346] = {DO_PUSH = 'PLAY'},
	[331] = {DO_PUSH = 'PLAYPAUSE'},
	[351] = {DO_PUSH = 'START_SCAN_REV', DO_RELEASE = 'STOP_SCAN_REV', DO_CLICK = 'STOP_SCAN_REV'},
	[352] = {DO_PUSH = 'ROOM_OFF'},
	[354] = {DO_PUSH = 'SKIP_REV'},
	[355] = {DO_PUSH = 'SKIP_FWD'},
	[356] = {DO_PUSH = 'STOP'},
	[358] = {DO_PUSH = 'START_VOL_DOWN', DO_RELEASE = 'STOP_VOL_DOWN', DO_CLICK = 'STOP_VOL_DOWN'},
	[359] = {DO_PUSH = 'START_VOL_UP', DO_RELEASE = 'STOP_VOL_UP', DO_CLICK = 'STOP_VOL_UP'},
	[317] = {DO_PUSH = 'START_CH_UP', DO_RELEASE = 'STOP_CH_UP', DO_CLICK = 'STOP_CH_UP'},
	[316] = {DO_PUSH = 'START_CH_DOWN', DO_RELEASE = 'STOP_CH_DOWN', DO_CLICK = 'STOP_CH_DOWN'},
	[342] = {DO_PUSH = 'START_PAGE_DOWN', DO_RELEASE = 'STOP_PAGE_DOWN', DO_CLICK = 'STOP_PAGE_DOWN'},
	[343] = {DO_PUSH = 'START_PAGE_UP', DO_RELEASE = 'STOP_PAGE_UP', DO_CLICK = 'STOP_PAGE_UP'},
	[300] = {DO_PUSH = 'DASH'},
	[301] = {DO_PUSH = 'POUND'},
	[302] = {DO_PUSH = 'STAR'},
	[313] = {DO_PUSH = 'BACK'},
	[314] = {DO_PUSH = 'PROGRAM_D'},
	[315] = {DO_PUSH = 'CANCEL'},
	[318] = {DO_PUSH = 'CLOSED_CAPTIONED'},
	[319] = {DO_PUSH = 'CONTROL4'},
	[320] = {DO_PUSH = 'CUSTOM_1'},
	[321] = {DO_PUSH = 'CUSTOM_2'},
	[322] = {DO_PUSH = 'CUSTOM_3'},
	[323] = {DO_PUSH = 'PVR'},
	[324] = {DO_PUSH = 'EJECT'},
	[325] = {DO_PUSH = 'EXIT'},
	[327] = {DO_PUSH = 'FUNCTION'},
	[328] = {DO_PUSH = 'PROGRAM_B'},
	[329] = {DO_PUSH = 'GUIDE'},
	[330] = {DO_PUSH = 'INFO'},
	[332] = {DO_PUSH = 'MENU'},
	[336] = {DO_PUSH = 'DOWN'},
	[337] = {DO_PUSH = 'LEFT'},
	[338] = {DO_PUSH = 'RIGHT'},
	[339] = {DO_PUSH = 'UP'},
	[340] = {DO_PUSH = 'OPEN_CLOSE'},
	[341] = {DO_PUSH = 'ORDER'},
	[345] = {DO_PUSH = 'PIP'},
	[347] = {DO_PUSH = 'POWER'},
	[348] = {DO_PUSH = 'RECALL'},
	[349] = {DO_PUSH = 'RECORD'},
	[350] = {DO_PUSH = 'PROGRAM_A'},
	[353] = {DO_PUSH = 'ENTER'},
	[361] = {DO_PUSH = 'PROGRAM_C'},
}

-- Human-readable aliases that are not already implied by BUTTONS.
-- Button DO_* commands and START_/STOP_-stripped names are indexed automatically.
local COMMAND_ALIASES = {
	['0'] = 303,
	['1'] = 304,
	['2'] = 305,
	['3'] = 306,
	['4'] = 307,
	['5'] = 308,
	['6'] = 309,
	['7'] = 310,
	['8'] = 311,
	['9'] = 312,
	FAST_FORWARD = 326,
	FF = 326,
	FWD = 326,
	REWIND = 351,
	REV = 351,
	VOLUME_UP = 359,
	VOLUME_DOWN = 358,
	CHANNEL_UP = 317,
	CHANNEL_DOWN = 316,
	SKIP_BACK = 354,
	SKIP_FORWARD = 355,
	PLAY_PAUSE = 331,
	SELECT = 353,
	OK = 353,
	RED = 350,
	GREEN = 328,
	YELLOW = 361,
	BLUE = 314,
}

-- Extra room commands not represented by a standard button binding.
local EXTRA_COMMANDS = {
	EXIT_NAVIGATION = true,
	SELECT_AUDIO_DEVICE = true,
	SELECT_AUDIO_MEDIA = true,
	SELECT_VIDEO_DEVICE = true,
	SET_VOLUME_LEVEL = true,
	START_DOWN = true,
	START_LEFT = true,
	START_RIGHT = true,
	START_UP = true,
	STOP_DOWN = true,
	STOP_LEFT = true,
	STOP_RIGHT = true,
	STOP_UP = true,
}
